package com.xlhb.pojo;

import java.util.Date;

public class Prizeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.id
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.studentid
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private Integer studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.sort
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.name
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.measure
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private String measure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.reason
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeinfo.date
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.id
     *
     * @return the value of prizeinfo.id
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.id
     *
     * @param id the value for prizeinfo.id
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.studentid
     *
     * @return the value of prizeinfo.studentid
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.studentid
     *
     * @param studentid the value for prizeinfo.studentid
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.sort
     *
     * @return the value of prizeinfo.sort
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.sort
     *
     * @param sort the value for prizeinfo.sort
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.name
     *
     * @return the value of prizeinfo.name
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.name
     *
     * @param name the value for prizeinfo.name
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.measure
     *
     * @return the value of prizeinfo.measure
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.measure
     *
     * @param measure the value for prizeinfo.measure
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.reason
     *
     * @return the value of prizeinfo.reason
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.reason
     *
     * @param reason the value for prizeinfo.reason
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeinfo.date
     *
     * @return the value of prizeinfo.date
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeinfo.date
     *
     * @param date the value for prizeinfo.date
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}