package com.xlhb.mapper;

import com.xlhb.pojo.Prizeinfo;
import com.xlhb.pojo.PrizeinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrizeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    int countByExample(PrizeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    int deleteByExample(PrizeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    int insert(Prizeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    int insertSelective(Prizeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    List<Prizeinfo> selectByExample(PrizeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Prizeinfo record, @Param("example") PrizeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeinfo
     *
     * @mbggenerated Tue Apr 16 16:38:54 CST 2019
     */
    int updateByExample(@Param("record") Prizeinfo record, @Param("example") PrizeinfoExample example);
}